# Лабораторная работа 1
## Язык Python, библиотеки NumPy и Pandas для анализа данных.

ФИО: Кривов Кирилл Иванович

Группа: 8О-308Б

In [ ]:
import numpy as np
import pandas as pd

## Часть 1: Python

#### 1. Напишите код, который сформирует список всех натуральных чисел, не превосходящих 100, которые делятся на 7 и не делятся на 5. Нельзя использовать циклы — выполните это задание с помощью list comprehension.

In [1]:
[x for x in range(1, 101) if not x % 7 and x % 5]

[7, 14, 21, 28, 42, 49, 56, 63, 77, 84, 91, 98]

#### 2. Напишите функцию `sort_tokens(s)`, которая принимает на вход строку, разделяет ее на токены по запятым, сортирует токены с помощью функции `sorted()` и снова соединяет их в одну строку через запятые. Например, для строки `u"ночь,фонарь,улица"` функция должна выдать `u"ночь,улица,фонарь"`. Придумайте несколько входных строк и протестируйте функцию на них.

Обратите внимание, что склеить строки можно с помощью конструкции `'x'.join(...)`. Например:

In [ ]:
'! '.join(['i', 'am', 'very', 'excited', ':-)'])

In [2]:
def sort_tokens(s):
    return ','.join(sorted(s.split(',')))
print sort_tokens("ночь,фонарь,улица")
print sort_tokens("1,a,2,b,3,c,6,C,5,B,4,A")

ночь,улица,фонарь
1,2,3,4,5,6,A,B,C,a,b,c


#### 3. Напишите функцию `remove_duplicates(a)`, которая принимает на вход список и возвращает его же, но без дубликатов и в отсортированном виде. Например, для списка `[u"ночь", u"улица", u"фонарь", u"аптека", u"аптека", u"улица", u"фонарь"]` результат должен быть `[u"аптека", u"ночь", u"улица", u"фонарь", ]`.

Подсказка: обратите внимание на структуру `set`!

In [3]:
def remove_duplicates(a):
    return sorted(set(a))
print ', '.join(remove_duplicates([u"ночь", u"улица", u"фонарь", u"аптека", u"аптека", u"улица", u"фонарь"]))

аптека, ночь, улица, фонарь


#### 4. Напишите функцию `word_counts(texts)`, которая принимает на вход список строк, и печатает пары (слово, число вхождений). Считайте, что слова в текстах могут быть разделены только пробелами. Например, для входа `[u'ночь улица фонарь аптека', u'аптека улица фонарь']` должно быть напечатано
>аптека 2

>улица 2

>фонарь 2

>ночь 1

Подсказки:

Чтобы разбить каждый из текстов на слова, воспользуйтесь функцией `map`, которая применяет заданную функцию к каждому элементу списка. Например, если бы нужно было каждый из текстов привести к нижнему регистру, то команда выглядела бы так:

In [ ]:
map(lambda x: x.lower(), ["abCDefg", "HIjkL"])

После первого шага вы получите список, состоящий из списков слов. Чтобы объединить их в один список слов, воспользуйтесь функцией `reduce`. Например, просуммировать числа из списка с ее помощью можно так:



In [ ]:
reduce(lambda x, y: x + y, [1, 2, 3, 4, 5])

Для подсчета количества вхождений слов воспользуйтесь структурой `defaultdict` из модуля `collections`. В отличие от обычного `dict`, она не генерирует ошибку при обращении к несуществущему ключу, а создает новую запись, инициализируемую нулевым значением. Например:

In [ ]:
from collections import defaultdict
d = defaultdict(int)
print d
d['abc'] += 1
print d
d['xxx']
print d

In [4]:
from collections import defaultdict

def word_counts(text):
    d = defaultdict(int)
    words = map(lambda x: x.lower().split(), text)
    words = reduce(lambda x, y: x + y, words)
    for i in words:
        d[i] += 1
    return d

d = word_counts([u'ночь улица фонарь аптека', u'аптека улица фонарь'])
for s, num in d.items():
    print "%s\t- %s" % (s, num) 


аптека	- 2
улица	- 2
фонарь	- 2
ночь	- 1


#### 5. Проанализируйте английский перевод "Преступления и наказания". Найдите 20 самых популярных слов и 20 слов, которые встречаются только один раз.

Приведите текст к нижнему регистру. Разделите текст на слова, считая разделителями все, кроме букв. Обратите внимание на функцию `split` из модуля `re`.

Не забудьте удалить пустые слова:
```
words = filter(lambda x: len(x) > 0, words)
```

In [ ]:
from urllib import urlopen
url = "http://www.gutenberg.org/files/2554/2554.txt"
response = urlopen(url)
raw_text = response.read().decode('utf8')
raw_text[1000:1100]

In [5]:
from urllib import urlopen
import re
from collections import defaultdict

url = "http://www.gutenberg.org/files/2554/2554.txt"

def proc_text(url):
    response = urlopen(url)
    raw_text = response.read().decode('utf8')

    d = defaultdict(int)

    words = re.split('\W', raw_text)
    words = filter(lambda x: len(x) > 0, words)
    words = map(lambda x: x.lower(), words)
    
    for w in words:
        d[w] += 1
            
    l1, l2 = [], []
    for word, num in sorted(d.items(), key=lambda x: -x[1]):
        if len(l1) < 20:
            l1.append(word)
        if num == 1:
            l2.append(word)
    return l1, l2
    
top20, top1 = proc_text(url)
print "20:"
print ', '.join(top20)
print "1:"
print ', '.join(top1[:20] if len(top1) > 20 else top1)

20:
the, and, to, he, a, i, you, of, it, that, in, was, his, at, her, but, not, s, with, she
1:
fawn, writings, nunnery, fedosya, clotted, preface, cyprus, increase, _might_, wheeled, superficially, _when, meadows, fogeys, anaemic, straws, busybody, reliable, scraped, errors


## Часть 2: NumPy и SciPy

#### 1. Повторите 1000 раз следующий эксперимент: сгенерируйте две матрицы размера $10 \times 10$ из стандартного нормального распределения, перемножьте их (как матрицы) и найдите максимальный элемент. Какое среднее значение по экспериментам у максимальных элементов? А 95-процентная квантиль?

Для вычисления квантили воспользуйтесь функцией `np.percentile`

In [1]:
import numpy as np

def exp(n, mu, sigma):
    m1 = np.matrix(np.random.normal(mu, sigma, (n, n)))
    m2 = np.matrix(np.random.normal(mu, sigma, (n, n)))
    return np.dot(m1, m2).max()

num_of_exp = 1000
a = np.array([exp(10, 0, 1) for _ in xrange(num_of_exp)])
mean = a.mean()
percentile = np.percentile(a, 95)
print mean, percentile

8.3558375019 11.7105232658


#### 2. Сгенерируйте 1000 чисел из распределения Пуассона с параметром $\lambda = 5$. Сформируйте массив, в котором в i-м элементе будет записано количество сгенерированных чисел, равных i.

Обратите внимание на функцию `np.bincount`

In [7]:
import numpy as np

lam = 5
size = 1000
a = np.bincount(np.random.poisson(lam, (size,)))
print a

[  4  30  85 150 201 170 132 110  59  31  14   9   3   1   1]


#### 3. Реализуйте функцию, которая принимает на вход numpy-массив целых чисел `a`, и генерирует массив, в котором число `i` встречается `a[i]` раз. Протестируйте на результате из прошлого задания.

Обратите внимание на функцию `np.repeat`

In [8]:
import numpy as np

def gen_arr(a):
    return np.repeat(np.arange(len(a)), a)

lam = 5
size = 1000
test_arr = np.random.poisson(lam, (size,))
a1 = np.bincount(test_arr)
a2 = np.bincount(gen_arr(a1))
print "All works fine:", (a1 == a2).all()

All works fine: True


#### 4. Напишите функцию `scale(X)`, которая принимает на вход матрицу и масштабирует каждый ее столбец (вычитает среднее и делит на стандартное отклонение). Убедитесь, что в функции не будет происходить деления на ноль. Протестируйте на каких-нибудь данных.

In [2]:
import numpy as np

def scale(mtrx):
    means = np.mean(mtrx, axis=0)
    devs = np.std(mtrx, axis=0)
    devs[devs == 0] = 1
    return (mtrx - means) / devs

def test(m):
    m = scale(m)
    print "============"
    print m
    print "vec of means:\n", np.mean(m, axis=0)
    print "vec of std:\n", np.std(m, axis=0)
    
m1 = np.matrix(np.random.normal(3, 42, (5, 5)))
test(m1)

m2 = np.matrix([[5, 2, 0],
                [15, 2, 0],
                [7, 2, 0]])
test(m2)

[[ 0.76773945 -0.08141495 -1.85056378  0.85827919 -1.15052918]
 [-1.83233103  0.2752502   0.21564117 -0.33962968  1.45088577]
 [ 0.2432452   0.69555061 -0.08421349  0.70367197 -0.50449645]
 [ 0.98367667 -1.86566349  1.00807091  0.59420629 -0.70287102]
 [-0.1623303   0.97627763  0.71106519 -1.81652777  0.90701089]]
vec of means:
[[ -2.22044605e-17   2.22044605e-17   2.22044605e-17   4.44089210e-17
   -2.22044605e-17]]
vec of std:
[[ 1.  1.  1.  1.  1.]]
[[-0.9258201   0.          0.        ]
 [ 1.38873015  0.          0.        ]
 [-0.46291005  0.          0.        ]]
vec of means:
[[ 0.  0.  0.]]
vec of std:
[[ 1.  0.  0.]]


#### 5. Сгенерируйте матрицу с элементами из нормального распределения $\mathcal{N}(10, 1)$. Найдите ее:
- определитель (determinant)
- след (trace)
- наименьший и наибольший элементы
- собственные числа
- обратную матрицу

In [10]:
import numpy as np
import numpy.linalg as la

mtrx = np.matrix(np.random.normal(10, 1, (5, 5)))
print "det = %d" % la.det(mtrx)
print "trace = %d" % np.trace(mtrx)
print "max = %d, min = %d" % (mtrx.max(), mtrx.min())
print "eigvals = ", la.eigvals(mtrx)
print "inverse = ", la.inv(mtrx)

det = -119
trace = 46
max = 11, min = 8
eigvals =  [ 49.67569611+0.j          -1.16426169+2.15476146j  -1.16426169-2.15476146j
   0.45846691+0.j          -0.87173199+0.j        ]
inverse =  [[-0.31127175 -0.26882501  0.29277503  0.59047695 -0.27630479]
 [ 0.42764354  1.03116683  0.01255411 -2.63698259  1.17964262]
 [-0.90649459 -1.3967905  -0.57386976  4.70133941 -1.82351288]
 [ 0.02677055 -0.23485344  0.27987483 -0.25434604  0.22436074]
 [ 0.79892805  0.9453581   0.00849561 -2.51045688  0.77430807]]


## Часть 3: Pandas

#### Ответьте на вопросы о данных по авиарейсам в США за январь-апрель 2008 года.

Данные: http://stat-computing.org/dataexpo/2009/2008.csv.bz2
(обратите внимание, что распаковывать этот файл не обязательно — функция `pandas.read_csv` умеет читать из архивов автоматически)

Описание: http://stat-computing.org/dataexpo/2009/the-data.html

1. Какая из причин отмены рейса (`CancellationCode`) была самой частой? (расшифровки кодов можно найти в описании данных)
2. Найдите среднее, минимальное и максимальное расстояние, пройденное самолетом.
3. Не выглядит ли подозрительным минимальное пройденное расстояние? В какие дни и на каких рейсах оно было? Какое расстояние было пройдено этими же рейсами в другие дни?
4. Из какого аэропорта было произведено больше всего вылетов? В каком городе он находится?
5. Найдите для каждого аэропорта среднее время полета (`AirTime`) по всем вылетевшим из него рейсам. Какой аэропорт имеет наибольшее значение этого показателя?
6. Найдите аэропорт, у которого наибольшая доля задержанных (`DepDelay > 0`) рейсов. Исключите при этом из рассмотрения аэропорты, из которых было отправлено меньше 1000 рейсов (используйте функцию `filter` после `groupby`).

In [11]:
from pandas import *
from collections import defaultdict, Counter
import numpy as np


url = "http://stat-computing.org/dataexpo/2009/2008.csv.bz2"
path_bz2 = "./2008.csv.bz2"

# from http://stat-computing.org/dataexpo/2009/supplemental-data.html
path_airports = "./airports.csv"

CANC_C = 'CancellationCode'
DIS = 'Distance'
OR = 'Origin'
AT = 'AirTime'
DM = 'DayofMonth'
DW = 'DayOfWeek'
MO = 'Month'
DD = 'DepDelay'
FN = 'FlightNum'

CANCEL_CODE_CAUSES = dict(A = 'carrier', B = 'weather', C = 'NAS', D = 'security')

In [13]:
# 1
cancellation_code_counter = Counter()

reader = read_csv(path_bz2, compression='bz2', chunksize=100000)
for chunk in reader:
    for i in chunk[CANC_C].dropna():
        cancellation_code_counter[i] += 1
    
print "# 1"
print "The most common cause of cancel was:", \
        CANCEL_CODE_CAUSES[cancellation_code_counter.most_common(1)[0][0]]
    
del cancellation_code_counter
del reader, chunk

# 1
The most common cause of cancel was: weather


In [14]:
# 2
distance_arr = np.array([])

reader = read_csv(path_bz2, compression='bz2', chunksize=100000)
for chunk in reader:
    distance_arr = np.append(distance_arr, np.array(chunk[DIS]))
    
print "# 2"
print "Max distance = %d miles\nmin distance = %d miles\nmean distance = %d miles" % (distance_arr.max(),
                                                                                      distance_arr.min(),
                                                                                      distance_arr.mean())

min_dist = distance_arr.min() #  for cell below

del distance_arr
del reader, chunk

# 2
Max distance = 4962 miles
min distance = 11 miles
mean distance = 726 miles


In [15]:
# 3
# required min_dist var from cell above

min_dist_info = DataFrame(columns=[FN, DM, MO])
other_flights = DataFrame(columns=[FN, DIS, DM, MO])

reader = read_csv(path_bz2, compression='bz2', chunksize=100000)
for chunk in reader:
    tmp = chunk.loc[:, [FN, DM, MO]][chunk[DIS] == min_dist]
    min_dist_info = min_dist_info.append(tmp)
    tmp = chunk.loc[:, [FN, DM, MO, DIS]][chunk[FN].isin(tmp[FN])]
    other_flights = other_flights.append(tmp)
    
other_flights = other_flights[~other_flights.isin(min_dist_info)].dropna(how='all', subset=[FN, DM, MO])
    
print "# 3"
print "Min distance flight info:\n"
print min_dist_info
print "\nSame flight info:\n"
print other_flights.sort_values(DIS)

del min_dist_info, other_flights
del reader, chunk

# 3
Min distance flight info:

       FlightNum  DayofMonth  Month
47298       4988          15      5
92215       5572          10      8

Same flight info:

       DayofMonth  Distance  FlightNum  Month
89314           5       544       5572      8
90571           7       544       5572      8
91200           8       544       5572      8
91679           9       544       5572      8
92214          10       544       5572      8
92834          11       544       5572      8
93421          12       544       5572      8
94045          13       544       5572      8
94677          14       544       5572      8
95309          15       544       5572      8
95786          16       544       5572      8
96327          17       544       5572      8
96949          18       544       5572      8
97462          19       544       5572      8
98047          20       544       5572      8
98666          21       544       5572      8
89938           6       544       5572      8
99286        

In [16]:
# 4 and 5
origin_counter = Counter()
origin_air_times = defaultdict(lambda: np.array([]))

reader = read_csv(path_bz2, compression='bz2', chunksize=100000)
for chunk in reader:
    for i in chunk.groupby([OR])[AT]:
        origin_air_times[i[0]] = np.append(origin_air_times[i[0]], np.array(i[1].dropna()))
        origin_counter[i[0]] += len(i[1])

iata_df = read_csv(path_airports)

print "# 4"
most_common_iata = origin_counter.most_common(1)[0][0]
print "Most departures was from the airport:", most_common_iata
print "City:", iata_df[iata_df.iata == most_common_iata]['city'].values[0]
    
print "#5"
print "Average air time for each airport (in minutes):"
for i, j in sorted(origin_air_times.items(), key=lambda x: x[1].mean(), reverse=True):
    print "%s - %s" % (i, j.mean())
    
del origin_counter, origin_air_times
del reader, chunk

# 4
Most departures was from the airport: ATL
City: Atlanta
#5
Average air time for each airport (in minutes):
SJU - 203.850842697
BQN - 190.857996019
PSE - 184.336927224
STT - 168.681928547
STX - 168.101176471
JFK - 167.355979889
ANC - 156.16374855
SEA - 154.814355907
ADK - 151.423913043
EWR - 143.296556471
MIA - 142.526073122
IAD - 135.594889175
PHL - 133.680779173
SWF - 132.768826201
BOS - 132.636955033
SFO - 132.337412244
FLL - 130.374548193
ISP - 129.134457115
LAX - 128.85933658
HPN - 128.567018291
RFD - 128.235087719
LGB - 127.073576623
MCO - 127.008346729
RSW - 126.046256575
PBI - 125.329374476
PDX - 123.19615708
LAS - 119.734438057
HNL - 119.579008715
BDL - 118.701611783
MDW - 118.226172519
TPA - 117.917963188
IAH - 115.20484777
PHX - 115.005586252
MHT - 112.813902452
MSP - 111.436247943
SAN - 110.930818973
DEN - 109.944494124
ACY - 108.848214286
PVD - 108.444756767
LGA - 107.180078153
BWI - 106.413994906
DFW - 106.406896779
SNA - 105.176326478
OGG - 103.784145907
SRQ - 103.083

In [17]:
# 6
df_or_dd = DataFrame(columns=[OR, DD])

reader = read_csv(path_bz2, compression='bz2', chunksize=100000)
for chunk in reader:
    df_or_dd = df_or_dd.append(chunk.loc[:, [OR, DD]])
    
print "# 6"
df_or_dd_filter = df_or_dd[df_or_dd[DD] > 0].groupby([OR]).filter(lambda x: len(x) > 1000).groupby([OR])
df_or_dd = df_or_dd.groupby([OR]).size()
ratios = Counter()
for i in df_or_dd_filter:
    ratios[i[0]] = float(len(i[1])) / df_or_dd[i[0]]
print "Answer:", ratios.most_common(1)[0][0]

del df_or_dd, df_or_dd_filter, ratios
del reader, chunk

# 6
Answer: DAL
